apiVersion: v1
kind: Service
metadata:
  labels:
    app: hoarder-social-sharing
  name: hoarder-social-sharing
  namespace: hoarder
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hoarder-social-sharing
  type: ClusterIP
